name: deploy-container

on:
  push:
    branches:
      - master
    paths:
      - "container/**"

defaults:
  run:
    working-directory: container

jobs:
  build:
    runs-on: unabtu-latest

    steps:
      - uses: action/checkout@v2
      - run: npm install
      - run: npm run build
